server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /health {
    access_log off;
    return 200 "healthy\n";
    add_header Content-Type text/plain;
  }

  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location /api/serviceA/ {
    proxy_pass http://servicea:3001/serviceA;
  }

  location /api/serviceA/health {
    proxy_pass http://servicea:3001/health;
  }

  location /api/serviceB/ {
    proxy_pass http://serviceb:3002/serviceB;
  }

  location /api/serviceB/health {
    proxy_pass http://serviceb:3002/health;
  }

  location /api/serviceC/ {
    proxy_pass http://servicec:3003/serviceC;
  }

  location /api/serviceC/health {
    proxy_pass http://servicec:3003/health;
  }

  location /api/serviceD/ {
    proxy_pass http://serviced:3004/serviceD;
  }

  location /api/serviceD/health {
    proxy_pass http://serviced:3004/health;
  }

  location /api/serviceE/ {
    proxy_pass http://servicee:3005/serviceE;
  }

  location /api/serviceE/health {
    proxy_pass http://servicee:3005/health;
  }
}
