server {
    listen 80;

    # Frontend Routing
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend API Routing (Service A)
    location /api/servicea/ {
        proxy_pass http://servicea:3001/;
        proxy_set_header Host $host;
    }
    
    # Baaki services ke liye bhi isi tarah blocks banayein agar zaroorat ho
}